FINANCIAL_AI_USE_CASES = [
    {
        "id": "credit_scoring",
        "name": "Credit Scoring / Creditworthiness Assessment",
        "risk_level": "high_risk",
        "ai_act_reference": "Annex III, point 5(b)",
        "description": "AI systems used to evaluate creditworthiness of natural persons",
        "related_regulations": ["gdpr_art_22", "consumer_credit_directive"],
        "typical_actors": ["banks", "credit_institutions", "fintech_lenders"],
        "obligations": ["conformity_assessment", "human_oversight", "transparency", "fraia"],
    },
    {
        "id": "fraud_detection",
        "name": "Fraud Detection",
        "risk_level": "context_dependent",
        "ai_act_reference": "Art. 6(3)",
        "description": "AI systems for detecting fraudulent transactions",
        "related_regulations": ["psd2", "aml_directive"],
        "typical_actors": ["banks", "payment_providers", "insurers"],
        "obligations": ["depends_on_classification"],
    },
    {
        "id": "aml_kyc",
        "name": "AML/KYC Screening",
        "risk_level": "context_dependent",
        "ai_act_reference": "Art. 6(3)",
        "description": "AI for anti-money laundering and know-your-customer checks",
        "related_regulations": ["aml_directive_6", "dora"],
        "typical_actors": ["banks", "investment_firms", "crypto_providers"],
        "obligations": ["depends_on_classification"],
    },
    {
        "id": "algorithmic_trading",
        "name": "Algorithmic Trading",
        "risk_level": "minimal_or_limited",
        "ai_act_reference": "Not explicitly listed in Annex III",
        "description": "AI systems for automated trading decisions",
        "related_regulations": ["mifid2_art_17"],
        "typical_actors": ["investment_firms", "hedge_funds"],
        "obligations": ["general_purpose_if_applicable", "mifid_specific"],
    },
    {
        "id": "robo_advisory",
        "name": "Robo-Advisory / Automated Investment Advice",
        "risk_level": "context_dependent",
        "ai_act_reference": "Art. 6(3) - may be high-risk",
        "description": "AI providing investment recommendations to retail clients",
        "related_regulations": ["mifid2_suitability", "idd"],
        "typical_actors": ["investment_firms", "banks", "fintech"],
        "obligations": ["transparency", "possibly_high_risk"],
    },
    {
        "id": "insurance_pricing",
        "name": "Insurance Risk Assessment & Pricing",
        "risk_level": "high_risk",
        "ai_act_reference": "Annex III, point 5(c)",
        "description": "AI for life/health insurance risk assessment and premium setting",
        "related_regulations": ["solvency2", "idd", "gdpr"],
        "typical_actors": ["insurers", "reinsurers"],
        "obligations": ["conformity_assessment", "human_oversight", "transparency", "fraia"],
    },
    {
        "id": "claims_processing",
        "name": "Insurance Claims Processing",
        "risk_level": "context_dependent",
        "ai_act_reference": "Art. 6(3)",
        "description": "AI for automated claims assessment and processing",
        "related_regulations": ["solvency2", "gdpr_art_22"],
        "typical_actors": ["insurers"],
        "obligations": ["depends_on_classification"],
    },
    {
        "id": "customer_chatbot",
        "name": "Customer Service Chatbot",
        "risk_level": "limited_risk",
        "ai_act_reference": "Art. 50(1)",
        "description": "AI chatbots interacting with customers",
        "related_regulations": ["gdpr", "consumer_rights_directive"],
        "typical_actors": ["all_financial_institutions"],
        "obligations": ["transparency_disclosure"],
    },
    {
        "id": "internal_risk_models",
        "name": "Internal Risk Models (IRB, Internal Models)",
        "risk_level": "context_dependent",
        "ai_act_reference": "May fall under Art. 6(3)",
        "description": "AI-enhanced models for regulatory capital calculation",
        "related_regulations": ["crd_crr", "solvency2"],
        "typical_actors": ["banks", "insurers"],
        "obligations": ["existing_sectoral_requirements_may_suffice"],
    },
]

ROLES_IN_AI_VALUE_CHAIN = [
    {
        "id": "provider",
        "name": "AI Provider",
        "ai_act_definition": "Art. 3(3)",
        "description": "Develops or has AI system developed and places it on market or puts into service under own name/trademark",
        "financial_examples": [
            "Vendor selling credit scoring AI to banks",
            "Fintech developing fraud detection",
        ],
        "key_obligations": [
            "Conformity assessment (Art. 43)",
            "Technical documentation (Art. 11)",
            "Quality management system (Art. 17)",
            "Registration in EU database (Art. 49)",
            "Post-market monitoring (Art. 72)",
        ],
    },
    {
        "id": "deployer",
        "name": "AI Deployer",
        "ai_act_definition": "Art. 3(4)",
        "description": "Uses AI system under its authority (except personal non-professional use)",
        "financial_examples": [
            "Bank using vendor's credit scoring AI",
            "Insurer using third-party fraud detection",
        ],
        "key_obligations": [
            "Use according to instructions (Art. 26)",
            "Human oversight (Art. 26(2))",
            "Input data relevance (Art. 26(4))",
            "Monitoring and incident reporting (Art. 26(5))",
            "FRAIA for high-risk (Art. 27)",
            "Inform individuals (Art. 26(11))",
        ],
    },
    {
        "id": "provider_and_deployer",
        "name": "Provider & Deployer (In-House Development)",
        "ai_act_definition": "Art. 25",
        "description": "Financial institution that develops AND uses its own AI system",
        "financial_examples": [
            "Large bank developing proprietary credit model",
            "Insurer building internal risk AI",
        ],
        "key_obligations": ["All provider obligations", "All deployer obligations"],
    },
    {
        "id": "importer",
        "name": "Importer",
        "ai_act_definition": "Art. 3(6)",
        "description": "Places on EU market an AI system from third country provider",
        "financial_examples": [
            "EU subsidiary of US bank importing parent's AI system"
        ],
        "key_obligations": [
            "Verify conformity assessment done (Art. 23)",
            "Verify CE marking and documentation (Art. 23)",
            "Keep copy of documentation (Art. 23)",
        ],
    },
]
